### ISSUE TITLE
Script to create a new naming authority repo

### ISSUE THREAD

**Issue by candeynasa** [spase-group/spase-scripts#1]
We need a script to create new naming authority repositories in [https://github.com/orgs/hpde/repositories](https://github.com/orgs/hpde/repositories) with pre-populated directories, LICENSE, Readme, workflows. Also change Github permissions and settings, and add the repo to other workflows such as adding to hpde.io.  Todd may have such a script already.

**Comment by cfdolan** [comment]
Please describe pre-populated directories, Github permissions/settings details.

**Comment by candeynasa** [comment]
I'm hoping Lee and Todd will be able to identify what's been done in the past.

**Comment by tressahelvey** [comment]
@cfdolan @candeynasa 
Has this been completed??

**Comment by cfdolan** [comment]
This was put in place last September:
https://github.com/hpde/naming-auth-template

From: tressahelvey ***@***.***>
Date: Tuesday, July 16, 2024 at 8:31 AM
To: spase-group/spase-scripts ***@***.***>
Cc: Dolan, Charles F. (GSFC-672.0)[ADNET SYSTEMS INC] ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [spase-group/spase-scripts] Script to create a new naming authority repo (Issue #1)
CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



@cfdolan<https://github.com/cfdolan> @candeynasa<https://github.com/candeynasa>
Has this been completed??

**Comment by tressahelvey** [comment]
This was put in place last September: 
https://github.com/hpde/naming-auth-template
